### ISSUE TITLE
Feature Request keeping temp plan output

### ISSUE THREAD

**Issue by victorgetz** [minamijoyo/tfmigrate#36]
Hi,

it would be awesome if we could have the option to keep the temp plan output file from /tmp/....
We would like to use it as a input for our Terraform plan stage.

**Comment by minamijoyo** [comment]
I'm a bit confused because the issue title is about a temp state file, on the other hand the description is about a temp plan file. Which one is correct?

**Comment by victorgetz** [comment]
Sorry if you are in a meeting and making feature request at the same time then this bullshit comes out.

Often in real big projects you need to migrate states and create new resources. For Example you are switching your terraform modules to a central registry.

I like the idea of your tool, but in my opinion it lacks two features if you want to use it with CI/CD.

I want to reconstruct our pipelines like this:
![image](https://user-images.githubusercontent.com/19291722/126945080-0541ade2-1a51-448d-9d4f-52e843fd81bb.png)

This two features would be nice:

1. Force tfmigrate plan (even when there is no state migration but new resources will be created/deleted...)
2. keep the plan output from /tmp/.... to use it as a input for tfmigrate apply or tf apply

**Comment by minamijoyo** [comment]
OK, you intended a temp plan file.

For 1, the `force` parameter has already implemented as a `migration` block attribute.
For 2, it's ok to add a new flag `tfmigrate plan -out=foo.tfplan` to store a temp plan file as a given path, which can be passed to `terraform apply foo.tfplan`.

**Comment by minamijoyo** [comment]
For 1, I misunderstood your request, but I feel it's out of scope for tfmigrate.
For 2, I started writing a naive implementation in #37. It's still WIP yet. Stay tuned.

**Comment by minamijoyo** [comment]
While implementing this feature in #37, it turned out that it's not so simple problem as I thought.

A saved plan file internally contains terraform configurations which used by plan. The tfmigrate uses a temporary local backend configuration not to change a remote state in plan phase. This means that applying the saved plan also uses the local backend and it doesn't save the state to the remote backend. We may be possible to push the local state to remote, but the lineage of the state was changed, it requires force push. It will be unsafe operation.

**Comment by minamijoyo** [comment]
@victorgetz Added it in v0.2.7. There are some precautions for use. Please read #37.
